kind: Pod
apiVersion: v1
metadata:
  name: wema-pvc
spec:
  containers:
    - name: my-frontend
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-claim