#Local volume using nodeAffinity - create a local path /mnt/disks
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: disk
          operator: In
          values:
          - sshd
